# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    webhook:
        routing:
            mailer_resend:
                service: 'mailer.webhook.request_parser.resend'
                secret: '%env(MAILER_RESEND_SECRET)%'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
